### ISSUE TITLE
.AVI as Streamable Video

### ISSUE THREAD

**Issue by halkatmanus** [SpEcHiDe/PublicLeech#94]
Feature Request:
Convert to Stream bots upload .avi files as Streamable Videos.
Could you please add the feature to upload .avi files as Streamable Videos just like .mkv and .mp4.
Thank You 🙏🏻

**Comment by SpEcHiDe** [comment]
Telegram does not support AVI files as streamable, to the best of my knowledge. 

What the "popular" bots are "apparently"** doing is re-encoding, which costs un-necassary server resources, and I think it is not in scope of this project.

**: n.b.: I know there is no way to verify my claim, since the "popular" robots are not open-source. 🤷‍♂
